config/routes.rb
CrmBranchcore::Application.routes.draw do

root :to => 'access#sign_in'  

match 'access/sign_in' => 'access#sign_in'
match 'access/sign_up' => 'access#sign_up'
match 'access/logout' => 'access#logout'
match 'access/attempt_login' => 'access#attempt_login'

namespace :admin do

  root :to => 'users#index'
  resources :users, :except => [:show] do
    member do
     get 'delete'
    end

  end

  resources :contacts do
    member do
      get 'delete'
    end
  end

  resources :business_types do

    member do
      get 'delete'
    end

  end

  resources :accounts do

    member do
      get 'delete'
    end

  end

  resources :opportunities do

    member do
      get 'delete'
    end

  end

  resources :tasks do

    member do
      get 'delete'
    end

  end
  
end
  
  

end

app/models/account.rb
class Account < ActiveRecord::Base

self.per_page = 10;

 
belongs_to :user
belongs_to :business_type
has_many :opportunities

EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i  

validates :user, :presence=>true  
validates :business_type, :presence=>true  
validates :account_type, :presence=>true 
validates :name, :presence=>true, :length => { :maximum => 40 }
validates :email,:presence=>true, :uniqueness => true, :format => EMAIL_REGEX, :length => { :maximum => 100 }  
validates :address, :presence=>true, :length => {:minimum=>15, :maximum => 1000 }
validates :description, :presence=>true, :length => {:minimum=>15, :maximum => 1000 }


attr_accessible :name, :email, :address, :description, :account_type, :user ,:user_id, :business_type ,:business_type_id

end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController

  layout "admin"
  
    before_filter :confirm_logged_in
  
  def  index

    @accounts= Account.paginate(:page => params[:page])

    render "list"

  end

  def list

    @accounts= Account.paginate(:page => params[:page])

    respond_to do |format|

      format.html
      format.xml {render :xml => @accounts}

    end

  end

  def new

    @account = Account.new
    @users = User.order('id ASC')
    @business_types = BusinessType.order('id ASC')

  end

  def create

    @account = Account.new(params[:account])

    if @account.save

      flash[:notice] = "Account created"

      redirect_to admin_accounts_path

    else

      @users = User.order('id ASC')
      @business_types = BusinessType.order('id ASC')
      render "new"

    end
  end

  def edit
    @account = Account.find(params[:id])
    @users = User.order('id ASC')
    @business_types = BusinessType.order('id ASC')

  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(params[:account])
      flash[:notice] = 'Account updated.'
      redirect_to admin_accounts_path
    else
      @users = User.order('id ASC')
      @business_types = BusinessType.order('id ASC')
      render("edit")
    end
  end

  def delete
    @account = Account.find(params[:id])
  end

  def destroy
    Account.find(params[:id]).destroy
    flash[:notice] = "Account deleted."
    redirect_to admin_accounts_path
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/admin/accounts/_form.html.erb
<% if @account.errors.any? %>
<ul class="alert alert-error error_form_list">
	<% @account.errors.full_messages.each do |msg| %>
	<li>
		<%= msg %>
	</li>
	<% end %>
</ul>
<% end %>

<%= form_for([:admin,@account], :html =>{:class=>"form-horizontal"}) do |f| %>

	<div class="control-group">
		<%= f.label :user_id, "User",:class=>"control-label" %>
		<div class="controls">
			<%= f.select(:user_id, @users.collect {|s| [s.name, s.id]},{:prompt => 'Select a user'}) %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :business_type_id, "Bussiness Type",:class=>"control-label" %>
		<div class="controls">
			<%= f.select(:business_type_id, @business_types.collect {|s| [s.sector, s.id]},{:prompt => 'Select a business type'}) %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :account_type, :class=>"control-label" %>
		<div class="controls">
			<%= f.select :account_type, options_for_select([["Select an account type",""],["Small", "SMALL"], ["Big", "BIG"]]) %>
		</div>
	</div>



	<div class="control-group">
		<%= f.label :name, :class=>"control-label" %>
		<div class="controls">
			<%= f.text_field :name %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :email, :class=>"control-label" %>
		<div class="controls">
			<%= f.text_field :email %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :address, :class=>"control-label" %>
		<div class="controls">
			<%= f.text_area  :address, :class=>"adress_text_area" %>
		</div>
	</div>
	
	<div class="control-group">
		<%= f.label :description, :class=>"control-label" %>
		<div class="controls">
			<%= f.text_area  :description, :class=>"adress_text_area" %>
		</div>
	</div>

	<div class="form-buttons pull-right" >
				<%= link_to("Back to List", admin_accounts_path, :class => 'btn btn-inverse') %>
				<%= f.submit  :class =>"btn btn-primary" %>
	</div>


<% end %> 

app/views/admin/accounts/delete.html.erb
<div class="row-fluid">
	<div class="span4 offset4">
<% @page_title = "Delete Account #{@account.name}" %>


<div class="user delete">
  <h2>Delete Account</h2>
  

    <p>Are you sure you want to permanently delete this Account?</p>
  
    <p class="reference-name"><%= @account.name %></p>
  
    <div class="form-buttons">
    	<%= link_to("Back to List", admin_accounts_path, :class => 'btn btn-inverse') %>
      <%= link_to "Delete", [:admin, @account],:method => :delete, :class => "btn btn-danger" %>
    </div>
    
 </div>
</div>
</div>

app/views/admin/accounts/edit.html.erb
<div class="row-fluid">
	<div class="span6 offset3" >
		<% @page_title = 'Edit Account' %>

		
			
<div class="well">
			
			<legend>Edit Account</legend>	
			<%= render 'form' %>
			
			
<br />
				
		</div>

	</div>

</div>

app/views/admin/accounts/list.html.erb
<div class="row-fluid">
	<div class="span10 offset1">
		<h1>Listing Accounts</h1>

		<table class="table table-hover">
		<thead>
		<tr>
		<th>Id</th>	
		<th>Name</th>
		<th>Email</th>
		<th class="hidden-tablet">Type</th>
		<th>User</th>
		<th class="hidden-tablet">Business Type</th>

		<th>Actions</th>
		</tr>
		</thead>
		<tbody>
		<% @accounts.each do |account| %>
		<tr>
		<td><%= account.id %></td>	
		<td><%= account.name %></td>
		<td><%= account.email %></td>
		<td class="hidden-tablet"><%= account.account_type %></td>
		<td><%= account.user ? account.user.name : "N/A"  %></td>
		<td class="hidden-tablet"><%= account.business_type ? account.business_type.sector : "N/A"  %></td>

		<td>

	 			<%= link_to "Edit", edit_admin_account_path(account), :class=>"btn btn-info" %>
				<%= link_to "Delete", delete_admin_account_path(account), :class=>"btn btn-danger" %>
				
		</td>

		</tr>
		<% end %>
		</tbody>
	
	</table>


		<div class="other_actions">
			<%= link_to "Add Account", new_admin_account_path , :class => "btn btn-primary" %>
	
			
			<%= will_paginate @accounts %>
			
		</div>

		<br />
	</div>
</div>

app/views/admin/accounts/new.html.erb
<div class="row-fluid">
	<div class="span6 offset3" >
		<% @page_title = 'Create Account' %>

		
			
<div class="well">
			
			<legend>New Account</legend>	
			<%= render 'form' %>
			
			
<br />
				
		</div>

	</div>

</div>