config/routes.rb
CrmBranchcore::Application.routes.draw do

root :to => 'access#sign_in'  

match 'access/sign_in' => 'access#sign_in'
match 'access/sign_up' => 'access#sign_up'
match 'access/logout' => 'access#logout'
match 'access/attempt_login' => 'access#attempt_login'

namespace :admin do

  root :to => 'users#index'
  resources :users, :except => [:show] do
    member do
     get 'delete'
    end

  end

  resources :contacts do
    member do
      get 'delete'
    end
  end

  resources :business_types do

    member do
      get 'delete'
    end

  end

  resources :accounts do

    member do
      get 'delete'
    end

  end

  resources :opportunities do

    member do
      get 'delete'
    end

  end

  resources :tasks do

    member do
      get 'delete'
    end

  end
  
end
  
  

end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  
    belongs_to :user
    belongs_to :account
    
    self.per_page = 10;
  
    attr_accessible :user,:user_id, :account,:account_id,:amount,:status,:description
    
    validates :user, :presence=>true  
    validates :account, :presence=>true  
    validates :status, :presence=>true 
    
    validates :amount, :presence => true, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => true
    validates :description, :presence=>true, :length => {:minimum=>15, :maximum => 1000 }
end

app/controllers/admin/opportunities_controller.rb
class Admin::OpportunitiesController < ApplicationController
  
  
   layout "admin"
  
  
  
    before_filter :confirm_logged_in
    
    
  def  index
    
    @opportunities= Opportunity.paginate(:page => params[:page])
    
    render "list"

  end

  def list

    @opportunities= Opportunity.paginate(:page => params[:page])

    respond_to do |format|

      format.html
      format.xml {render :xml => @opportunities}

    end

  end

  def new

    @opportunity = Opportunity.new
    @users = User.order('id ASC')
    @accounts = Account.order('id ASC')

  end

  def create

    @opportunity = Opportunity.new(params[:opportunity])

    if @opportunity.save

      flash[:notice] = "Opportunity created"

      redirect_to admin_opportunities_path

    else
    @users = User.order('id ASC')
    @accounts = Account.order('id ASC')
      render "new"

    end
  end

  def edit
    @opportunity = Opportunity.find(params[:id])
    @users = User.order('id ASC')
     @accounts = Account.order('id ASC')

  end

  def update
    @opportunity = Opportunity.find(params[:id])
    if @opportunity.update_attributes(params[:opportunity])
      flash[:notice] = 'Opportunity updated.'
      redirect_to admin_opportunities_path
    else
      @users = User.order('id ASC')
      @accounts = Account.order('id ASC')
      render("edit")
    end
  end

  def delete
    @opportunity = Opportunity.find(params[:id])
  end

  def destroy
    Opportunity.find(params[:id]).destroy
    flash[:notice] = "Opportunity deleted."
    redirect_to admin_opportunities_path
  end

  
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/views/admin/opportunities/_form.html.erb
<% if @opportunity.errors.any? %>
<ul class="alert alert-error error_form_list">
	<% @opportunity.errors.full_messages.each do |msg| %>
	<li>
		<%= msg %>
	</li>
	<% end %>
</ul>
<% end %>

	<%= form_for([:admin, @opportunity], :html =>{:class=>"form-horizontal"}) do |f| %>

	<div class="control-group">
		<%= f.label :user_id, "User",:class=>"control-label" %>
		<div class="controls">
			<%= f.select(:user_id, @users.collect {|s| [s.name, s.id]},{:prompt => 'Select a user'}) %>
		</div>
	</div>

<div class="control-group">
		<%= f.label :account_id, "Account",:class=>"control-label" %>
		<div class="controls">
			<%= f.select(:account_id, @accounts.collect {|s| [s.name, s.id]},{:prompt => 'Select an account'}) %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :status, :class=>"control-label" %>
		<div class="controls">
			<%= f.select :status, options_for_select([["Select a status",""],["Active", "ACTIVE"], ["Inactive", "INACTIVE"]]) %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :amount, :class=>"control-label" %>
		<div class="controls">
			<%= f.text_field :amount %>
		</div>
	</div>

	
	<div class="control-group">
		<%= f.label :description, :class=>"control-label" %>
		<div class="controls">
			<%= f.text_area  :description, :class=>"adress_text_area" %>
		</div>
	</div>


<div class="form-buttons pull-right" >
				<%= link_to("Back to List", admin_opportunities_path, :class => 'btn btn-inverse') %>
				<%= f.submit :class =>"btn btn-primary" %>
</div>


<% end %>

app/views/admin/opportunities/delete.html.erb
<div class="row-fluid">
	<div class="span4 offset4">
<% @page_title = "Delete Opportunity with: #{@opportunity.account.name}" %>


<div class="user delete">
  <h2>Delete Opportunity</h2>
  
 
    <p>Are you sure you want to permanently delete this opportunity?</p>
  
    <p class="reference-name"> <%= @opportunity.description %> </p>
  
    <div class="form-buttons">
    	<%= link_to("Back to List", admin_opportunities_path, :class => 'btn btn-inverse') %>
      <%= link_to 'Delete Opportunity',[:admin,@opportunity],:method => :delete, :class =>"btn btn-primary" %>
    </div>
 
</div>
</div>
</div>

app/views/admin/opportunities/edit.html.erb
<div class="row-fluid">
	<div class="span6 offset3" >
		<% @page_title = 'Edit Opportunity' %>

		
			
<div class="well">
		
			<legend>Edit Opportunity</legend>	
			
			<%= render 'form' %>
			
			
<br />
	
		</div>

	</div>

</div>

app/views/admin/opportunities/list.html.erb
<div class="row-fluid">
	<div class="span10 offset1">
		<h1>Listing Opportunities</h1>

		<table class="table table-hover">
		<thead>
		<tr>
		<th>Id</th>	
		<th>Responsable User</th>
		<th>Linked Account</th>
		<th>Amount</th>
		<th class="hidden-tablet">Status</th>
		<th>Actions</th>
		</tr>
		</thead>
		<tbody>
		<% @opportunities.each do |opportunity| %>
		<tr>
		<td><%= opportunity.id %></td>	
		<td><%= opportunity.user ? opportunity.user.name : "N/A"  %></td>
		<td><%= opportunity.account ? opportunity.account.name : "N/A"  %></td>
		<td><%= opportunity.amount %></td>
		<td class="hidden-tablet"><%= opportunity.status %></td>

		<td>
	
	 			<%= link_to "Edit", edit_admin_opportunity_path(opportunity), :class=>"btn btn-info" %>
				<%= link_to "Delete", delete_admin_opportunity_path(opportunity), :class=>"btn btn-danger" %>
				
	
		</td>

		</tr>
		<% end %>
		</tbody>
	
	</table>


		<div class="other_actions">
			

			<%= link_to "New Opportunity", new_admin_opportunity_path, :class => "btn btn-primary" %>			
			<%= will_paginate @opportunities %>
			
		</div>

		<br />
	</div>
</div>

app/views/admin/opportunities/new.html.erb
<div class="row-fluid">
	<div class="span6 offset3" >
		<% @page_title = 'New Opportunity' %>

		
			
<div class="well">
		
			<legend>New Opportunity</legend>	
			<%= render 'form' %>
			
			
<br />
	
		</div>

	</div>

</div>