config/routes.rb
CrmBranchcore::Application.routes.draw do

root :to => 'access#sign_in'  

match 'access/sign_in' => 'access#sign_in'
match 'access/sign_up' => 'access#sign_up'
match 'access/logout' => 'access#logout'
match 'access/attempt_login' => 'access#attempt_login'

namespace :admin do

  root :to => 'users#index'
  resources :users, :except => [:show] do
    member do
     get 'delete'
    end

  end

  resources :contacts do
    member do
      get 'delete'
    end
  end

  resources :business_types do

    member do
      get 'delete'
    end

  end

  resources :accounts do

    member do
      get 'delete'
    end

  end

  resources :opportunities do

    member do
      get 'delete'
    end

  end

  resources :tasks do

    member do
      get 'delete'
    end

  end
  
end
  
  

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  # attr_accessible :title, :body
  
has_many :contacts
has_many :accounts
has_many :opportunities

self.per_page = 10;
  
attr_accessor :password 
  
attr_accessible  :first_name, :last_name, :username, :password,:password_confirmation, :email, :email_confirmation, :is_admin

EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i  
  
validates :first_name,:presence=>true, :length => { :maximum => 40 }
validates :last_name,:presence=>true, :length => { :maximum => 40 }
validates :password,:presence=>true, :length => { :maximum => 25 }, :confirmation => true
validates :email,:presence=>true, :uniqueness => true, :format => EMAIL_REGEX, :confirmation => true,:length => { :maximum => 100 }  

 before_save :create_hashed_password
 after_save :clear_password


  def name
    "#{first_name} #{last_name}"
  end  
  
 attr_protected :hashed_password, :salt
  
  def name
    "#{first_name} #{last_name}"
  end
  
  def self.authenticate(username="", password="")
    user = User.find_by_username(username)
    if user && user.password_match?(password)
      return user
    else
      return false
    end
  end

  # The same password string with the same hash method and salt
  # should always generate the same hashed_password.
  def password_match?(password="")
    hashed_password == User.hash_with_salt(password, salt)
  end
  
  def self.make_salt(username="")
    Digest::SHA1.hexdigest("Use #{username} with #{Time.now} to make salt")
  end
  
  def self.hash_with_salt(password="", salt="")
    Digest::SHA1.hexdigest("Put #{salt} on the #{password}")
  end
  
  private
  
  def create_hashed_password
    # Whenever :password has a value hashing is needed
    unless password.blank?
      # always use "self" when assigning values
      self.salt = User.make_salt(username) if salt.blank?
      self.hashed_password = User.hash_with_salt(password, salt)
    end
  end

  def clear_password
    # for security and b/c hashing is not needed
    self.password = nil
  end  
  
  
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  layout "admin"
  
    before_filter :confirm_logged_in
  
  def index
    @users= User.paginate(:page => params[:page])
    render "list"
  end
  
  
  
  def list
    
   @users= User.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end

  end


  def new

    @user = User.new

  end

  def create

    @user = User.new(params[:user])
    if @user.save

      flash[:notice] = 'User created.'

      redirect_to admin_users_path

    else
      render("new")
    end

  end

  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = 'User updated.'
      redirect_to admin_users_path
    else
      render("edit")
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "User deleted."
   redirect_to admin_users_path
  end
  
 
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout "admin"
  
    before_filter :confirm_logged_in
  
  def index
    @users= User.paginate(:page => params[:page])
     render "list"
  end
  
  
  
  def list
    
   @users= User.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end

  end


  def new

    @user = User.new

  end

  def create

    @user = User.new(params[:user])
    if @user.save

      flash[:notice] = 'User created.'

      redirect_to(:action => 'list')

    else
      render("new")
    end

  end

  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = 'User updated.'
      redirect_to(:action => 'list')
    else
      render("edit")
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "Admin user destroyed."
    redirect_to(:action => 'list')
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
<ul class="alert alert-error error_form_list">
	<% @user.errors.full_messages.each do |msg| %>
	<li>
		<%= msg %>
	</li>
	<% end %>
</ul>
<% end %>

<%= form_for [:admin, @user],:html =>{:class=>"form-horizontal"}  do |f| %>

<div class="control-group">
	<%= f.label :first_name, :class=>"control-label" %>
	<div class="controls">
		<%= f.text_field(:first_name) %>
	</div>
</div>

<div class="control-group">
	<%= f.label :last_name,:class=>"control-label" %>
	<div class="controls">
		<%= f.text_field(:last_name) %>
	</div>
</div>
<div class="control-group">
	<%= f.label :email, :class=>"control-label" %>
	<div class="controls">
		<%= f.text_field(:email) %>
	</div>
</div>

<div class="control-group">
	<%= f.label :email_confirmation, :class=>"control-label" %>
	<div class="controls">
		<%= f.text_field(:email_confirmation) %>
	</div>
</div>

<div class="control-group">
	<%= f.label :username, :class=>"control-label" %>
	<div class="controls">
		<%= f.text_field(:username) %>
	</div>
</div>
<div class="control-group">
	<%= f.label :password, :class=>"control-label" %>
	<div class="controls">
		<%= f.password_field(:password) %>
	</div>
</div>

<div class="control-group">
	<%= f.label :password_confirmation, :class=>"control-label" %>
	<div class="controls">
		<%= f.password_field(:password_confirmation) %>
	</div>
</div>

<div class="control-group">
	<%= f.label :is_admin, :class=>"control-label" %>
	<div class="controls">
		<%= f.check_box (:is_admin) %>
	</div>
</div>

<div class="form-buttons pull-right" >
		<%= link_to "Back to List", admin_users_path , :class => 'btn btn-inverse' %>
	<%= f.submit :class =>"btn btn-primary" %>
</div>

<% end %>

app/views/admin/users/delete.html.erb
<div class="row-fluid">
	<div class="span4 offset4">
<% @page_title = "Delete User: #{@user.name}" %>


<div class="user delete">
  <h2>Delete Admin User</h2>
  
    <p>Are you sure you want to permanently delete this user?</p>
  
    <p class="reference-name"><%= @user.name %></p>
  
    <div class="form-buttons">
    	<%= link_to "Back to List", admin_users_path , :class => 'btn btn-inverse' %>
		<%= link_to "Delete", [:admin,@user], :method => :delete,  :class => 'btn btn-danger' %>
		  	  

    </div>

</div>
</div>
</div>

app/views/admin/users/edit.html.erb
<div class="row-fluid">
	<div class="span6 offset3" >
		<% @page_title = 'Edit Admin User' %>

		<div class="well">

			<legend>
				Edit User
			</legend>

			<%= render 'form'  %>

			<br />

		</div>

	</div>

</div>

app/views/admin/users/list.html.erb
<div class="row-fluid">
	<div class="span10 offset1">
		<h1>Listing users</h1>

		<table class="table table-hover">
		<thead>
		<tr>
			<th>Id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>User Name</th>
			<th class="hidden-tablet">Email</th>
			<th>Is Admin?</th>
			<th>Actions</th>
		</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
			<tr>
			<td><%= user.id %></td>	
			<td><%= user.first_name %></td>
			<td><%= user.last_name %></td>
			<td><%= user.username %></td>
			<td class="hidden-tablet"><%= user.email %></td>
			<td><%= user.is_admin %></td>
			<td> 
								
					
	 			<%= link_to "Edit", edit_admin_user_path(user), :class=>"btn btn-info" %>
				<%= link_to "Delete", delete_admin_user_path(user), :class=>"btn btn-danger" %>
				
					
				
				
			</td>
			
			
			</tr>
			<% end %>
		</tbody>
		</table>
		
		
		<div class="other_actions">
			<%= link_to "New User", new_admin_user_path, :class => "btn btn-primary" %>
			<br />
				<%= will_paginate @users %>
		</div>	
		
		<br />
	</div>
</div>

app/views/admin/users/new.html.erb
<div class="row-fluid">
	<div class="span6 offset3" >
		<% @page_title = 'New User' %>

		<div class="well">

			<legend>
				Create User
			</legend>

			<%= render 'form'  %>

			<br />

		</div>

	</div>

</div>