config/routes.rb
CrmBranchcore::Application.routes.draw do

root :to => 'access#sign_in'  

match 'access/sign_in' => 'access#sign_in'
match 'access/sign_up' => 'access#sign_up'
match 'access/logout' => 'access#logout'
match 'access/attempt_login' => 'access#attempt_login'

namespace :admin do

  root :to => 'users#index'
  resources :users, :except => [:show] do
    member do
     get 'delete'
    end

  end

  resources :contacts do
    member do
      get 'delete'
    end
  end

  resources :business_types do

    member do
      get 'delete'
    end

  end

  resources :accounts do

    member do
      get 'delete'
    end

  end

  resources :opportunities do

    member do
      get 'delete'
    end

  end

  resources :tasks do

    member do
      get 'delete'
    end

  end
  
end
  
  

end

app/controllers/admin/business_types_controller.rb
class Admin::BusinessTypesController < ApplicationController
  layout "admin"
  
    before_filter :confirm_logged_in
  
  def index
    @business_types= BusinessType.paginate(:page => params[:page])
     render "list"
  end
  
  
  
  def list
    
   @business_types= BusinessType.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @business_types }
    end

  end


  def new

    @business_type = BusinessType.new

  end

  def create

    @business_type = BusinessType.new(params[:business_type])
    if @business_type.save

      flash[:notice] = 'Business Type created.'

      redirect_to admin_business_types_path

    else
      render("new")
    end

  end

  
  def edit
    @business_type = BusinessType.find(params[:id])
  end

  def update
    @business_type = BusinessType.find(params[:id])
    if @business_type.update_attributes(params[:business_type])
      flash[:notice] = 'Business Type updated.'
          redirect_to admin_business_types_path
    else
      render("edit")
    end
  end

  def delete
    @business_type = BusinessType.find(params[:id])
  end

  def destroy
    BusinessType.find(params[:id]).destroy
    flash[:notice] = "Business Type deleted."
         redirect_to admin_business_types_path
  end

end

app/helpers/business_types_helper.rb
module BusinessTypesHelper
end

app/views/admin/business_types/_form.html.erb
<% if @business_type.errors.any? %>
<ul class="alert alert-error error_form_list">
	<% @business_type.errors.full_messages.each do |msg| %>
	<li>
		<%= msg %>
	</li>
	<% end %>
</ul>
<% end %>
<%= form_for [:admin, @business_type], :html =>{:class=>"form-horizontal"} do |f| %>
<div class="control-group">
	<%= f.label :sector, :class=>"control-label" %>
	<div class="controls">
		<%= f.text_field(:sector) %>
	</div>
</div>

<div class="form-buttons pull-right" >

	<%= link_to("Back to List", admin_business_types_path, :class => 'btn btn-inverse') %>
	<%= f.submit :class =>"btn btn-primary" %>
</div>
<br />
<% end %>

app/views/admin/business_types/delete.html.erb
<div class="row-fluid">
	<div class="span4 offset4">
<% @page_title = "Delete Business Type: #{@business_type.sector}" %>


  <h2>Delete Business Type</h2>
  
  

    <p>Are you sure you want to permanently delete this business type?</p>
  
    <p class="reference-name"><%= @business_type.sector %></p>
  
    <div class="form-buttons">
    	<%= link_to("Back to List", admin_business_types_path, :class => 'btn btn-inverse') %>
      <%= link_to "Delete", [:admin,@business_type], :method => :delete,  :class => 'btn btn-danger' %>
    </div>

</div>
</div>

app/views/admin/business_types/edit.html.erb
<div class="row-fluid">
	<div class="span6 offset3" >
		<% @page_title = 'Edit Business Type' %>

		<div class="well">

			<legend>
				Edit Business Type
			</legend>

			<%= render 'form'  %>

			<br />

		</div>

	</div>

</div>

app/views/admin/business_types/list.html.erb
<div class="row-fluid">
	<div class="span10 offset1">
		<h1>Listing Business Types</h1>

		<table class="table table-hover"">
		<thead>
		<tr>
			<th>Id</th>
			<th>Sector</th>
			<th>Actions</th>
		</tr>
		</thead>
		<tbody>
			<% @business_types.each do |business_type| %>
			<tr>
			<td><%= business_type.id %></td>	
			<td><%= business_type.sector %></td>
			<td> 
				
			<%= link_to "Edit", edit_admin_business_type_path(business_type), :class=>"btn btn-info" %>
			<%= link_to "Delete",delete_admin_business_type_path(business_type), :class=>"btn btn-danger" %>
				
			</td>
			
			
			</tr>
			<% end %>
		</tbody>
		</table>
		
		
		<div class="other_actions">
			<%= link_to "New business type", new_admin_business_type_path, :class => "btn btn-primary" %>
			<br />
				<%= will_paginate @business_types %>
		</div>	
		
		<br />
	</div>
</div>

app/views/admin/business_types/new.html.erb
<div class="row-fluid">
	<div class="span6 offset3" >
		<% @page_title = 'New Business Type' %>

		<div class="well">

			<legend>
				New Business Type
			</legend>

			<%= render 'form'  %>

			<br />

		</div>

	</div>

</div>